# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

jobs:
  - job: AzureTest
    pool:
      vmImage: 'windows-latest'
      variables:
        buildConfiguration: 'Release'
    steps:
    - task: DotNetCoreCLI@2
      displayName: 'dotnet restore'
      inputs:
        command: restore
        projects: '**/*.csproj'
    - task: DotNetCoreCLI@2
      displayName: 'dotnet build'
      inputs:
        projects: '**/*.csproj'
        arguments: '--configuration Release'
    - task: DotNetCoreCLI@2
      displayName: 'dotnet publish'
      inputs:
        command: publish
        publishWebProjects: false
        projects: '**/*.csproj'
        arguments: '--configuration Release --output $(Build.ArtifactStagingDirectory)'
    - task: PublishBuildArtifacts@1
      displayName: 'Publish Artifact Zip'
      inputs:
        ArtifactName: 'AzureDeploy'
    - task: AzureWebApp@1
      displayName: Web App Deploy
      inputs:
        appType: webApp
        azureSubscription: 'AzCertification'
        appName: 'PipelineDotNetDemo'
        package: $(Build.ArtifactStagingDirectory)/*.zip
